spring.application.name:
  hibernate-physical-name-strategy-example

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATALAKE_JDBC_URL:jdbc:postgresql://localhost:5432/datalake}
    username: ${DATALAKE_DB_USERNAME:}
    password: ${DATALAKE_DB_PASSWORD:}

  jpa:
    hibernate:
#      naming:
#        physical-strategy: com.alexamy.example.hibernate.naming.component.CustomSchemaNamingStrategy
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#        physical-strategy: com.alexamy.example.hibernate.naming.component.CustomSchemaNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.physical_naming_strategy: com.alexamy.example.hibernate.naming.component.CustomSchemaNamingStrategy

app:
  datasource:
    book-db:
      schema: ${BOOKS_SCHEMA:book_store}
      table:
        books: ${BOOKS_TABLE_BOOKS:books}



logging:
  level:
#    org.hibernate: DEBUG
#    org.springframework: DEBUG
    com.iclinicemr: INFO